services:
  # PHPアプリケーションサーバー
  php:
    container_name: ph2-todolist-php
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./src:/var/www/html:cached
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini:ro
    depends_on:
      - db

  # Webサーバー（Nginx）
  web:
    container_name: ph2-todolist-web
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "8081:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www/html:cached
    depends_on:
      - php

  # データベースサーバー（MySQL）
  db:
    container_name: ph2-todolist-db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: posse
      MYSQL_CHARACTER_SET_SERVER: utf8mb4
      MYSQL_COLLATION_SERVER: utf8mb4_0900_ai_ci
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    command: >
      mysqld
      --skip-character-set-client-handshake



# ボリューム設定
volumes:
  mysql-data:
